# Generated by Django 2.0.1 on 2018-02-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20180218_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
