# Generated by Django 2.0.1 on 2018-02-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20180218_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='edu_fk',
            new_name='parent_resume',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='exp_fk',
            new_name='parent_resume',
        ),
    ]
