# Generated by Django 2.0.1 on 2018-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
